name: E2E

on:
  push:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl apply && wait
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1
      with:
        args: apply -f kube/job.yaml && kubectl wait --for=condition=ready pod -l app=pingpong --timeout=600s

  e2e-safari:
    runs-on: macos-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: kubectl port-forward
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1
      with:
        args: port-forward job/pingpong 1337:1337 && sleep 5
    - name: run e2e
      run: open -a Safari http://127.0.0.1:1337/browser/connect

  finish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: kubectl delete
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1
      with:
        args: wait --for=condition=complete --timeout=600s job/pingpong && kubectl delete -f kube/job.yaml
